
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROW COMMA COMPONENTS CONTEXT DEPENDENCIES EQUAL HAZARD IDENTIFIER KPI LBRACE LBRACKET NUMBER RBRACE RBRACKET SYSTEMprogram : system contextsystem : SYSTEM IDENTIFIER LBRACE components dependencies RBRACEcomponents : COMPONENTS LBRACE component_list RBRACEcomponent_list : component_list component\n                      | componentcomponent : IDENTIFIER LBRACKET SE_attr COMMA criticality_attr RBRACKET SEMI_optSE_attr : IDENTIFIER EQUAL NUMBERcriticality_attr : IDENTIFIER EQUAL NUMBERSEMI_opt : \n                | COMMAdependencies : DEPENDENCIES LBRACE dependency_list RBRACEdependency_list : dependency_list dependency\n                       | dependencydependency : IDENTIFIER ARROW IDENTIFIER LBRACKET alpha_attr COMMA beta_attr RBRACKET SEMI_optalpha_attr : IDENTIFIER EQUAL NUMBERbeta_attr : IDENTIFIER EQUAL NUMBERcontext : CONTEXT IDENTIFIER LBRACE HAZARD IDENTIFIER LBRACKET IDENTIFIER EQUAL LBRACKET IDENTIFIER COMMA IDENTIFIER RBRACKET COMMA IDENTIFIER EQUAL NUMBER RBRACKET SEMI_opt KPI IDENTIFIER SEMI_opt RBRACE'
    
_lr_action_items = {'SYSTEM':([0,],[3,]),'$end':([1,4,73,],[0,-1,-17,]),'CONTEXT':([2,17,],[5,-2,]),'IDENTIFIER':([3,5,12,15,18,19,20,22,23,24,27,28,31,32,38,39,40,48,49,51,53,54,61,62,64,70,],[6,7,16,21,25,21,-5,29,25,-13,-4,33,-12,36,42,44,45,-9,55,57,-10,-6,-9,65,-14,71,]),'LBRACE':([6,7,11,14,],[8,9,15,18,]),'COMPONENTS':([8,],[11,]),'HAZARD':([9,],[12,]),'DEPENDENCIES':([10,26,],[14,-3,]),'RBRACE':([13,19,20,23,24,27,30,31,48,53,54,61,64,71,72,],[17,26,-5,30,-13,-4,-11,-12,-9,-10,-6,-9,-14,-9,73,]),'LBRACKET':([16,21,35,36,],[22,28,39,40,]),'ARROW':([25,],[32,]),'EQUAL':([29,33,42,45,57,65,],[35,37,47,50,60,66,]),'COMMA':([34,41,44,46,48,56,59,61,68,71,],[38,-7,49,51,53,-15,62,53,53,53,]),'NUMBER':([37,47,50,60,66,],[41,52,56,63,67,]),'RBRACKET':([43,52,55,58,63,67,],[48,-8,59,61,-16,68,]),'KPI':([53,68,69,],[-10,-9,70,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'system':([0,],[2,]),'context':([2,],[4,]),'components':([8,],[10,]),'dependencies':([10,],[13,]),'component_list':([15,],[19,]),'component':([15,19,],[20,27,]),'dependency_list':([18,],[23,]),'dependency':([18,23,],[24,31,]),'SE_attr':([28,],[34,]),'criticality_attr':([38,],[43,]),'alpha_attr':([40,],[46,]),'SEMI_opt':([48,61,68,71,],[54,64,69,72,]),'beta_attr':([51,],[58,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> system context','program',2,'p_program','parser.py',8),
  ('system -> SYSTEM IDENTIFIER LBRACE components dependencies RBRACE','system',6,'p_system','parser.py',12),
  ('components -> COMPONENTS LBRACE component_list RBRACE','components',4,'p_components','parser.py',20),
  ('component_list -> component_list component','component_list',2,'p_component_list','parser.py',24),
  ('component_list -> component','component_list',1,'p_component_list','parser.py',25),
  ('component -> IDENTIFIER LBRACKET SE_attr COMMA criticality_attr RBRACKET SEMI_opt','component',7,'p_component','parser.py',32),
  ('SE_attr -> IDENTIFIER EQUAL NUMBER','SE_attr',3,'p_SE_attr','parser.py',37),
  ('criticality_attr -> IDENTIFIER EQUAL NUMBER','criticality_attr',3,'p_criticality_attr','parser.py',42),
  ('SEMI_opt -> <empty>','SEMI_opt',0,'p_SEMI_opt','parser.py',47),
  ('SEMI_opt -> COMMA','SEMI_opt',1,'p_SEMI_opt','parser.py',48),
  ('dependencies -> DEPENDENCIES LBRACE dependency_list RBRACE','dependencies',4,'p_dependencies','parser.py',51),
  ('dependency_list -> dependency_list dependency','dependency_list',2,'p_dependency_list','parser.py',55),
  ('dependency_list -> dependency','dependency_list',1,'p_dependency_list','parser.py',56),
  ('dependency -> IDENTIFIER ARROW IDENTIFIER LBRACKET alpha_attr COMMA beta_attr RBRACKET SEMI_opt','dependency',9,'p_dependency','parser.py',63),
  ('alpha_attr -> IDENTIFIER EQUAL NUMBER','alpha_attr',3,'p_alpha_attr','parser.py',67),
  ('beta_attr -> IDENTIFIER EQUAL NUMBER','beta_attr',3,'p_beta_attr','parser.py',72),
  ('context -> CONTEXT IDENTIFIER LBRACE HAZARD IDENTIFIER LBRACKET IDENTIFIER EQUAL LBRACKET IDENTIFIER COMMA IDENTIFIER RBRACKET COMMA IDENTIFIER EQUAL NUMBER RBRACKET SEMI_opt KPI IDENTIFIER SEMI_opt RBRACE','context',23,'p_context','parser.py',77),
]
